### ISSUE TITLE
Legislative sessions

### ISSUE THREAD

**Issue by fgregg** [datamade/municipal-scrapers-us#16]
@davidmooreppf what are the time spans for the nyc legislative sessions going back to 1999?

**Comment by davidmooreppf** [comment]
Let me know if this is what you're looking for - terms are four years; most-recent election was Nov. 2013 for session officially starting Jan. 2014 - so previous terms started 2010, 2006, 2002, etc. ... about 90% sure there's no sub-section of a four-year term (e.g. no "sessions" as in the 115th US Congress). 

Just in case, Wikipedia notes re: 2000: "Council members are elected every four years, except for two consecutive two year terms every twenty years to allow for redistricting between the terms due to the national census (starting in 2001 and 2003 for the 2000 Census and again in 2021 and 2023 for the 2020 Census).:

We can make our own choices in how much historical data to load, I didn't anticipate going back that far to '99 - so whatever's feasible and in accordance with your Chicago work. Ping me Skype or IM to chat more if you like.

**Comment by fgregg** [comment]
Thanks! Could you give me the exact dates.

**Comment by davidmooreppf** [comment]
Yep, can ask my contact at Council, as official Council website doesn't seem to have it, news reports are a bit fuzzy, and NYC Legistar shows a first "stated meeting" on 1/8/2014 (but I'm not positive that's the official date). 

I'll see if they have the dates back to '99 easily handy, but otherwise, would just past couple years do?

**Comment by fgregg** [comment]
we can start there, sure.

**Comment by davidmooreppf** [comment]
Best current answer is first day of Jan.: January 1st, 2014; January 1st, 2010; etc. 

Full response from att'y: "... all I can find is the following City Charter provision about Council Member terms. I guess the specification in that provision of four-year election rules starting in in 1977 translates into Council sessions starting in 1978, 82, 86, 90, 94, 98, 2002, 2006, 2010, 2014.
 
Charter § 25 a. The council members shall be elected at the general election in the year nineteen hundred seventy-seven and every fourth year thereafter and the term of office of each council member shall commence on the first day of January after the elections and shall continue for four years thereafter..."

**Comment by fgregg** [comment]
Closed by https://github.com/opencivicdata/scrapers-us-municipal/commit/9e75cf4a0c887cea30da7e82d227f5514faeb454
